// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cmd

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gcmd"

	_ "sync-canal-go/internal/logic/app"
	"sync-canal-go/internal/consts"
	"sync-canal-go/internal/service"
)

var (
	Main = gcmd.Command{
		Name:  "main",
		Usage: "main",
		Brief: "start mysql binlog sync service",
		Func: func(ctx context.Context, parser *gcmd.Parser) (err error) {
			// 打印版本号
			g.Log().Infof(ctx, "Sync Canal Go Version: %s", consts.Version)

			a := service.App()

			// 初始化监控系统（先注册 API 路由，确保优先级高于静态文件路由）
			a.InitMonitor(ctx)

			// 配置静态文件服务（前端 UI，后注册以确保 API 路由优先）
			a.SetupStaticFiles()

			// 异步启动 Canal 同步服务
			a.StartCanalSyncAsync()

			// 注册优雅关闭
			go a.WaitForShutdown()

			// 启动 HTTP 服务器
			g.Server().Run()
			return nil
		},
	}
)
