
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - registry.cn-heyuan.aliyuncs.com/gzdzh
    tagName: "sync-canal-go:v3.0.1"
    push: true
  build:
    # 构建名称
    # name: "sync-canal-go"
    # 输出目录
    path: "./bin"
    # 额外构建参数
    extra: ""
    # 包含静态资源
    # packSrc: "resource"
    # 打包输出文件
    packDst: "internal/packed/packed.go"
    # 版本信息
    # version: "v3.0.1"
    cgo: 0
    # 多平台构建（逗号分隔）
    arch: "amd64"
    system: "linux"

  gen:
    dao:
      - link: "mysql:sync_user:sync_password_123@tcp(127.0.0.1:13308)/dzh3136_go"
        descriptionTag: true


