// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sync

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"github.com/go-mysql-org/go-mysql/canal"
	"github.com/go-mysql-org/go-mysql/mysql"
	"github.com/go-mysql-org/go-mysql/replication"
	"github.com/go-mysql-org/go-mysql/schema"
	"github.com/gogf/gf/v2/frame/g"

	"sync-canal-go/internal/model/entity"
	"sync-canal-go/internal/service"
)

// ClickHouseTarget ClickHouse 同步目标
type ClickHouseTarget struct {
	chConn driver.Conn
	config *entity.TargetConfig
	sync   *entity.SyncConfig
}

// NewClickHouseTarget 创建 ClickHouse 目标
func NewClickHouseTarget(tc *entity.TargetConfig, sync *entity.SyncConfig) (service.SyncTarget, error) {
	if tc.ClickHouse == nil {
		return nil, fmt.Errorf("clickhouse config is required for target %s", tc.Name)
	}
	return &ClickHouseTarget{
		config: tc,
		sync:   sync,
	}, nil
}

// Connect 连接 ClickHouse
func (t *ClickHouseTarget) Connect(ctx context.Context) error {
	ch := t.config.ClickHouse
	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{fmt.Sprintf("%s:%d", ch.Host, ch.Port)},
		Auth: clickhouse.Auth{
			Database: ch.Database,
			Username: ch.User,
			Password: ch.Password,
		},
		Settings: clickhouse.Settings{
			"max_execution_time": 60,
		},
		DialTimeout: time.Second * 30,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
	})
	if err != nil {
		return fmt.Errorf("connect to clickhouse failed: %v", err)
	}

	if err := conn.Ping(ctx); err != nil {
		return fmt.Errorf("ping clickhouse failed: %v", err)
	}

	t.chConn = conn
	g.Log().Infof(ctx, "Connected to ClickHouse: %s:%d/%s", ch.Host, ch.Port, ch.Database)
	return nil
}

// Close 关闭连接
func (t *ClickHouseTarget) Close() error {
	if t.chConn != nil {
		return t.chConn.Close()
	}
	return nil
}

// OnRow 处理行变更事件
func (t *ClickHouseTarget) OnRow(e *canal.RowsEvent) error {
	if !isTableAllowed(e.Table.Name, t.config.Tables) {
		return nil
	}

	switch e.Action {
	case canal.InsertAction:
		return t.handleInsert(e)
	case canal.UpdateAction:
		return t.handleUpdate(e)
	case canal.DeleteAction:
		return t.handleDelete(e)
	}
	return nil
}

// handleInsert 处理 INSERT 事件
func (t *ClickHouseTarget) handleInsert(e *canal.RowsEvent) error {
	ctx := context.Background()
	sql := fmt.Sprintf("INSERT INTO %s.%s", t.config.ClickHouse.Database, e.Table.Name)

	batch, err := t.chConn.PrepareBatch(ctx, sql)
	if err != nil {
		g.Log().Errorf(ctx, "Prepare batch failed: %v", err)
		return err
	}

	for _, row := range e.Rows {
		values := convertRow(row)
		if err := batch.Append(values...); err != nil {
			g.Log().Errorf(ctx, "Append row failed: %v", err)
			continue
		}
	}

	if err := batch.Send(); err != nil {
		g.Log().Errorf(ctx, "Send batch failed: %v", err)
		return err
	}

	g.Log().Infof(ctx, "[%s] Inserted %d rows to %s.%s",
		t.config.Name, len(e.Rows), t.config.ClickHouse.Database, e.Table.Name)
	return nil
}

// handleUpdate 处理 UPDATE 事件
func (t *ClickHouseTarget) handleUpdate(e *canal.RowsEvent) error {
	ctx := context.Background()

	for i := 0; i < len(e.Rows); i += 2 {
		newRow := e.Rows[i+1]

		sql := fmt.Sprintf("INSERT INTO %s.%s", t.config.ClickHouse.Database, e.Table.Name)
		batch, err := t.chConn.PrepareBatch(ctx, sql)
		if err != nil {
			g.Log().Errorf(ctx, "Prepare batch failed: %v", err)
			continue
		}

		values := convertRow(newRow)
		if err := batch.Append(values...); err != nil {
			g.Log().Errorf(ctx, "Append row failed: %v", err)
			continue
		}

		if err := batch.Send(); err != nil {
			g.Log().Errorf(ctx, "Send batch failed: %v", err)
			continue
		}
	}

	g.Log().Infof(ctx, "[%s] Updated %d rows in %s.%s",
		t.config.Name, len(e.Rows)/2, t.config.ClickHouse.Database, e.Table.Name)
	return nil
}

// handleDelete 处理 DELETE 事件
func (t *ClickHouseTarget) handleDelete(e *canal.RowsEvent) error {
	ctx := context.Background()
	pkIndex := findPrimaryKeyIndex(e.Table)

	for _, row := range e.Rows {
		sql := fmt.Sprintf(
			"ALTER TABLE %s.%s DELETE WHERE id = ?",
			t.config.ClickHouse.Database,
			e.Table.Name,
		)

		if err := t.chConn.Exec(ctx, sql, row[pkIndex]); err != nil {
			g.Log().Errorf(ctx, "Delete failed: %v", err)
			continue
		}
	}

	g.Log().Infof(ctx, "[%s] Deleted %d rows from %s.%s",
		t.config.Name, len(e.Rows), t.config.ClickHouse.Database, e.Table.Name)
	return nil
}

// OnDDL 处理 DDL 事件
func (t *ClickHouseTarget) OnDDL(header *replication.EventHeader, nextPos mysql.Position, queryEvent *replication.QueryEvent) error {
	if queryEvent == nil {
		return nil
	}
	ctx := context.Background()
	query := string(queryEvent.Query)
	for _, table := range t.config.Tables {
		if strings.Contains(query, table) {
			g.Log().Infof(ctx, "[%s] DDL: %s", t.config.Name, query)
			break
		}
	}
	return nil
}

// Start 启动定时清理任务
func (t *ClickHouseTarget) Start() {
	if t.config.Schedule == nil || !t.config.Schedule.Enable {
		g.Log().Infof(context.Background(), "[%s] Periodic OPTIMIZE is disabled", t.config.Name)
		return
	}

	intervalMinutes := t.config.Schedule.Interval
	if intervalMinutes <= 0 {
		intervalMinutes = 1440
	}

	interval := time.Duration(intervalMinutes) * time.Minute

	go func() {
		ctx := context.Background()
		for {
			g.Log().Infof(ctx, "[%s] Next OPTIMIZE scheduled in %v", t.config.Name, interval)

			timer := time.NewTimer(interval)
			<-timer.C

			t.optimizeTable()
		}
	}()
}

// optimizeTable 执行表优化
func (t *ClickHouseTarget) optimizeTable() {
	ctx := context.Background()

	for _, table := range t.config.Tables {
		startTime := time.Now()

		g.Log().Infof(ctx, "[%s] Starting OPTIMIZE for table %s.%s",
			t.config.Name, t.config.ClickHouse.Database, table)

		sql := fmt.Sprintf("OPTIMIZE TABLE %s.%s FINAL", t.config.ClickHouse.Database, table)
		if err := t.chConn.Exec(ctx, sql); err != nil {
			g.Log().Warningf(ctx, "[%s] Optimize table %s failed: %v", t.config.Name, table, err)
			continue
		}

		elapsed := time.Since(startTime)
		g.Log().Infof(ctx, "[%s] OPTIMIZE completed for %s.%s in %v",
			t.config.Name, t.config.ClickHouse.Database, table, elapsed)
	}
}

// String 返回目标名称
func (t *ClickHouseTarget) String() string {
	return fmt.Sprintf("ClickHouse:%s", t.config.Name)
}

// isTableAllowed 检查表是否在目标允许列表中
func isTableAllowed(tableName string, tables []string) bool {
	for _, t := range tables {
		if t == tableName {
			return true
		}
	}
	return false
}

// findPrimaryKeyIndex 查找主键索引
func findPrimaryKeyIndex(table *schema.Table) int {
	for i, col := range table.Columns {
		if col.Name == "id" {
			return i
		}
	}
	return 0
}

// convertRow 转换行数据（追加 _version 时间戳）
func convertRow(row []any) []any {
	values := make([]any, len(row))
	copy(values, row)
	values = append(values, time.Now().UnixNano())
	return values
}
