// =================================================================================
// This is auto-generated by GoFrame CLI tool once. Fill this file as you wish.
// =================================================================================

package sync

import (
	"context"
	"time"

	"github.com/go-mysql-org/go-mysql/canal"
	"github.com/go-mysql-org/go-mysql/mysql"
	"github.com/go-mysql-org/go-mysql/replication"
	"github.com/gogf/gf/v2/frame/g"

	"sync-canal-go/internal/model/entity"
	"sync-canal-go/internal/service"
)

// sMultiHandler 多目标事件处理器，实现 canal.EventHandler
type sMultiHandler struct {
	canal.DummyEventHandler
	targets       []service.SyncTarget
	collector     service.ICollector
	lastFile      string
	lastPos       uint32
	lastEventTime time.Time // 最后事件时间（用于计算延迟）
}

// NewMultiHandler 创建多目标处理器
func NewMultiHandler(targets []service.SyncTarget, collector service.ICollector) *sMultiHandler {
	h := &sMultiHandler{
		targets:   targets,
		collector: collector,
	}
	// 注册目标到监控
	if collector != nil {
		for _, t := range targets {
			collector.RegisterTarget(t.String(), "clickhouse")
		}
	}
	return h
}

// OnRow 将行变更事件分发到所有目标
func (h *sMultiHandler) OnRow(e *canal.RowsEvent) error {
	startTime := time.Now()

	// 获取第一个目标的名称用于监控记录
	var primaryTarget string
	if len(h.targets) > 0 {
		primaryTarget = h.targets[0].String()
	}

	for _, target := range h.targets {
		if err := target.OnRow(e); err != nil {
			g.Log().Warningf(context.Background(),
				"Target %s handle row failed: %v", target.String(), err)

			// 记录错误到监控
			if h.collector != nil {
				h.collector.OnError(&entity.SyncError{
					Timestamp:  time.Now(),
					Level:      "ERROR",
					TargetName: target.String(),
					TableName:  e.Table.Name,
					Message:    err.Error(),
				})
			}
		} else {
			// 更新目标状态
			if h.collector != nil {
				h.collector.UpdateTargetStatus(target.String(), "connected")
			}
		}
	}

	// 记录事件到监控 - 使用目标名称而非数据库名
	if h.collector != nil {
		duration := time.Since(startTime).Milliseconds()
		h.collector.OnEvent(&entity.SyncEvent{
			Timestamp:  time.Now(),
			EventType:  string(e.Action),
			TargetName: primaryTarget, // 使用目标名称
			TableName:  e.Table.Name,
			RowsCount:  len(e.Rows),
			BinlogFile: h.lastFile,
			BinlogPos:  h.lastPos,
			DurationMs: int(duration),
			Success:    true,
		})
	}

	return nil
}

// OnRotate 处理 binlog 轮转
func (h *sMultiHandler) OnRotate(header *replication.EventHeader, e *replication.RotateEvent) error {
	ctx := context.Background()
	g.Log().Infof(ctx, "Rotate to %s:%d", string(e.NextLogName), e.Position)

	// 更新位置
	h.lastFile = string(e.NextLogName)
	h.lastPos = uint32(e.Position)

	// 计算延迟
	var delaySeconds int64
	if header != nil && header.Timestamp > 0 {
		eventTime := time.Unix(int64(header.Timestamp), 0)
		delaySeconds = max(0, int64(time.Since(eventTime).Seconds()))
		h.lastEventTime = eventTime
	}

	// 记录位置到监控
	if h.collector != nil {
		h.collector.OnPosition(&entity.SyncPosition{
			Timestamp:    time.Now(),
			TargetName:   "main",
			BinlogFile:   h.lastFile,
			BinlogPos:    h.lastPos,
			DelaySeconds: delaySeconds,
		})
	}

	return nil
}

// OnDDL 将 DDL 事件分发到所有目标
func (h *sMultiHandler) OnDDL(header *replication.EventHeader, nextPos mysql.Position, queryEvent *replication.QueryEvent) error {
	// 更新位置
	h.lastFile = nextPos.Name
	h.lastPos = uint32(nextPos.Pos)

	for _, target := range h.targets {
		if err := target.OnDDL(header, nextPos, queryEvent); err != nil {
			g.Log().Warningf(context.Background(),
				"Target %s handle DDL failed: %v", target.String(), err)
		}
	}
	return nil
}

// OnXID 处理事务提交
func (h *sMultiHandler) OnXID(header *replication.EventHeader, nextPos mysql.Position) error {
	// 更新位置
	h.lastFile = nextPos.Name
	h.lastPos = uint32(nextPos.Pos)

	// 计算延迟：当前时间 - 事件时间
	var delaySeconds int64
	if header != nil && header.Timestamp > 0 {
		// MySQL 事件时间戳是秒级，是 UTC 时间
		eventTime := time.Unix(int64(header.Timestamp), 0)
		now := time.Now()
		delaySeconds = max(0, int64(now.Sub(eventTime).Seconds()))
		h.lastEventTime = eventTime

		// 调试日志
		g.Log().Infof(context.Background(),
			"OnXID: binlog=%s:%d, header.Timestamp=%d, eventTime=%v (UTC), now=%v (Local), delaySeconds=%d",
			nextPos.Name, nextPos.Pos, header.Timestamp, eventTime.UTC(), now, delaySeconds)
	} else {
		g.Log().Warningf(context.Background(), "OnXID: header is nil or timestamp is 0")
	}

	// 记录位置到监控
	if h.collector != nil {
		h.collector.OnPosition(&entity.SyncPosition{
			Timestamp:    time.Now(),
			TargetName:   "main",
			BinlogFile:   h.lastFile,
			BinlogPos:    h.lastPos,
			DelaySeconds: delaySeconds,
		})
	}

	return nil
}

// StartTargets 启动所有目标的后台任务
func (h *sMultiHandler) StartTargets() {
	for _, target := range h.targets {
		target.Start()
	}
}

// CloseTargets 关闭所有目标
func (h *sMultiHandler) CloseTargets() {
	for _, target := range h.targets {
		if err := target.Close(); err != nil {
			g.Log().Warningf(context.Background(),
				"Target %s close failed: %v", target.String(), err)
		}
	}
}

// String 返回处理器名称
func (h *sMultiHandler) String() string {
	return "MultiHandler"
}
