// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sync

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"regexp"
	"syscall"
	"time"

	"github.com/go-mysql-org/go-mysql/canal"
	"github.com/gogf/gf/v2/frame/g"

	"sync-canal-go/internal/model/entity"
	"sync-canal-go/internal/service"
)

func init() {
	service.RegisterSync(New())
}

// sSync 同步服务实现
type sSync struct{}

// New 创建同步服务实例
func New() *sSync {
	return &sSync{}
}

// InitTimezone 初始化时区
func (s *sSync) InitTimezone() {
	if tz := os.Getenv("TZ"); tz != "" {
		if loc, err := time.LoadLocation(tz); err == nil {
			time.Local = loc
		} else if tz == "CST-8" {
			time.Local = time.FixedZone("CST", 8*3600)
		}
	}
}

// LoadConfig 加载配置文件
func (s *sSync) LoadConfig(ctx context.Context) (*entity.SyncConfig, *entity.CanalConfig, error) {
	// 加载同步配置
	var syncConfig entity.SyncConfig
	if err := g.Cfg().MustGet(ctx, "sync").Scan(&syncConfig); err != nil {
		return nil, nil, err
	}

	// 加载 Canal 配置
	var canalConfig entity.CanalConfig
	if err := g.Cfg().MustGet(ctx, "canal").Scan(&canalConfig); err != nil {
		return nil, nil, err
	}

	// 设置默认值
	s.setDefaults(&syncConfig, &canalConfig)

	g.Log().Infof(ctx, "Config loaded: %d targets", len(syncConfig.Targets))
	return &syncConfig, &canalConfig, nil
}

// setDefaults 设置配置默认值
func (s *sSync) setDefaults(syncConfig *entity.SyncConfig, canalConfig *entity.CanalConfig) {
	if syncConfig.BatchSize == 0 {
		syncConfig.BatchSize = 1000
	}
	if canalConfig.Flavor == "" {
		canalConfig.Flavor = "mysql"
	}

	// 设置 targets 默认值
	for i := range syncConfig.Targets {
		t := &syncConfig.Targets[i]
		if t.Schedule != nil && t.Schedule.Enable && t.Schedule.Interval == 0 {
			t.Schedule.Interval = 1440
		}
	}
}

// CreateCanal 创建 Canal
func (s *sSync) CreateCanal(syncConfig *entity.SyncConfig, canalConfig *entity.CanalConfig) (*canal.Canal, error) {
	// 从 database.default 获取 MySQL 连接信息
	ctx := context.Background()
	link := g.Cfg().MustGet(ctx, "database.default.link").String()
	if link == "" {
		return nil, fmt.Errorf("database.default.link not found in config")
	}

	cfg := canal.NewDefaultConfig()

	// 解析 MySQL 连接字符串: mysql:user:password@tcp(host:port)/database
	// 示例: mysql:sync_user:sync_password_123@tcp(127.0.0.1:13308)/dzh3136_go
	re := regexp.MustCompile(`^mysql:([^:]+):([^@]+)@tcp\(([^:]+):(\d+)\)/`)
	matches := re.FindStringSubmatch(link)
	if len(matches) != 5 {
		return nil, fmt.Errorf("failed to parse database link: %q", link)
	}
	user, password, host, port := matches[1], matches[2], matches[3], matches[4]

	cfg.Addr = fmt.Sprintf("%s:%s", host, port)
	cfg.User = user
	cfg.Password = password
	cfg.Flavor = canalConfig.Flavor
	cfg.ServerID = canalConfig.ServerId

	// 禁用 mysqldump (仅增量同步)
	cfg.Dump.ExecutionPath = ""

	// 只监听所有目标需要的表（取并集）
	allTables := s.allTables(syncConfig)
	for _, table := range allTables {
		cfg.IncludeTableRegex = append(cfg.IncludeTableRegex,
			fmt.Sprintf("%s\\.%s", syncConfig.Database, table))
	}

	c, err := canal.NewCanal(cfg)
	if err != nil {
		return nil, fmt.Errorf("create canal failed: %v", err)
	}

	return c, nil
}

// allTables 返回所有目标的表并集
func (s *sSync) allTables(c *entity.SyncConfig) []string {
	seen := make(map[string]bool)
	var tables []string
	for _, t := range c.Targets {
		for _, table := range t.Tables {
			if !seen[table] {
				seen[table] = true
				tables = append(tables, table)
			}
		}
	}
	return tables
}

// WaitForSignal 等待退出信号
func (s *sSync) WaitForSignal() os.Signal {
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	return <-sigChan
}

// LogShutdownInfo 记录关闭信息
func (s *sSync) LogShutdownInfo(ctx context.Context, c *canal.Canal) {
	sig := s.WaitForSignal()
	g.Log().Infof(ctx, "Received signal: %v, shutting down...", sig)

	// 保存断点
	currentPos, err := c.GetMasterPos()
	if err == nil {
		g.Log().Infof(ctx, "Current position: %s:%d", currentPos.Name, currentPos.Pos)
	}

	g.Log().Info(ctx, "Sync service stopped")
}

// CreateTargets 根据配置创建所有同步目标
func (s *sSync) CreateTargets(config *entity.SyncConfig) ([]service.SyncTarget, error) {
	var targets []service.SyncTarget
	ctx := context.Background()

	for _, tc := range config.Targets {
		var target service.SyncTarget
		var err error

		switch tc.Type {
		case "clickhouse":
			target, err = NewClickHouseTarget(&tc, config)
		case "elasticsearch":
			return nil, fmt.Errorf("elasticsearch target not implemented yet: %s", tc.Name)
		case "mysql":
			return nil, fmt.Errorf("mysql target not implemented yet: %s", tc.Name)
		default:
			return nil, fmt.Errorf("unknown target type: %s", tc.Type)
		}

		if err != nil {
			return nil, fmt.Errorf("create target %s failed: %v", tc.Name, err)
		}

		// 连接目标
		if err := target.Connect(ctx); err != nil {
			return nil, fmt.Errorf("connect target %s failed: %v", tc.Name, err)
		}

		g.Log().Infof(ctx, "Target connected: %s (%s)", tc.Name, tc.Type)
		targets = append(targets, target)
	}

	return targets, nil
}
